export const EXPANDABLE_NODE_WIDTH = 180;
export const EXPANDABLE_NODE_HEIGHT = 60;
export const EXPANDABLE_CLOUD_GAP = 30;
export const EXPANDABLE_CLOUD_PADDING = 15;
export const EXPANDABLE_CLOUD_HEADER_HEIGHT = 30;
