// Re-export all constants
export {
    NODE_COLORS,
    COLORBLIND_NODE_COLORS,
    WARNING_COLORS,
    COLORBLIND_WARNING_COLORS,
    HINT_COLORS,
    COMPLEXITY_COLORS,
    TRANSFORMATION_COLORS,
    UI_COLORS,
    EDGE_COLORS,
    EDGE_DASH_PATTERNS,
    BADGE_COLORS,
    CONDITION_COLORS,
    NODE_STROKE_COLORS,
    GLOW_COLORS,
    STATUS_COLORS,
    CLOSE_BUTTON_COLORS,
    SCROLLBAR_COLORS,
    COMPONENT_UI_COLORS,
    NODE_SURFACE,
    NODE_ACCENT_COLORS,
    getNodeColor,
    getNodeAccentColor,
    getWarningColor,
    getSeverityIcon,
    getEdgeDashPattern,
    setColorblindMode,
    getColorblindMode,
    getTransformationColor,
    getScrollbarColors,
    getComponentUiColors,
} from './colors';
